---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "testops.fullname" . }}
  labels:
    app: {{ template "testops.fullname" . }}
    version: v1
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
{{ toYaml .Values.strategy | indent 4 }}
  selector:
    matchLabels:
      app: {{ template "testops.fullname" . }}
      version: v1
  template:
    metadata:
      labels:
        app: {{ template "testops.fullname" . }}
        version: v1
{{- if .Values.labels.deployment }}
{{- range $key, $value := .Values.labels.deployment }}
        {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}
{{- if .Values.annotations.deployment }}
      annotations:
{{- range $key, $value := .Values.annotations.deployment }}
        {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}
    spec:
{{- if .Values.rbac.enabled }}
      serviceAccountName:  {{ .Values.rbac.serviceAccountName }}
{{- end }}
{{- if .Values.image.authRequired.enabled }}
      imagePullSecrets:
{{- if .Values.image.authRequired.useExternalSecret }}
        - name: {{ .Values.image.authRequired.externalSecretName }}
{{- else }}
        - name: {{ .Values.image.authRequired.credsKubeSecretName }}
{{- end }}
{{- end }}
{{- if .Values.hostAliases }}
      hostAliases:
{{- toYaml .Values.hostAliases | nindent 8 }}
{{- end }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
{{- if .Values.affinity }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
{{- end }}
{{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
{{- end }}
      initContainers:
        - name: db-readiness-check
          image: {{ .Values.databaseInit.image | quote }}
{{- with .Values.databaseInit.resources }}
          resources:
{{ toYaml . | indent 12 }}
{{- end }}
{{- if .Values.containerSecurityContext.enabled }}
          securityContext: {{- omit .Values.containerSecurityContext "enabled" | toYaml | nindent 12 }}
{{- end }}
          command: [ 'sh', '-c',
            'until pg_isready -h {{ template "mainDBHost" . }} -p {{ template "mainDBPort" . }};
             do echo waiting for database; sleep 2; done;' ]
{{- if .Values.certificates.configmapName }}
        - name: certs-init
          image: amazoncorretto:17
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /bin/sh
            - -c
            - |
              mkdir -p /etc/pki/ca-trust/extracted/{java,pem,openssl,edk2} &&
              update-ca-trust &&
              keytool -alias trust-bundle.pem -import -keystore /etc/pki/ca-trust/extracted/java/cacerts -file /etc/pki/ca-trust/source/anchors/trust-bundle.pem -storepass changeit -noprompt
          volumeMounts:
            - name: ssl-path
              mountPath: "/etc/pki/ca-trust/extracted"
            - name: certs
              mountPath: /etc/pki/ca-trust/source/anchors
              readOnly: true
          securityContext:
            runAsUser: 0
{{- end }}
      containers:
{{- $secret_name := include "testops.secret.name" . }}
        - name: {{ template "testops.fullname" . }}
          image: "{{ template "getImageRegistry" . }}:{{ .Values.version | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
{{- if .Values.containerSecurityContext.enabled }}
          securityContext: {{- omit .Values.containerSecurityContext "enabled" | toYaml | nindent 12 }}
{{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.port }}
          env:
{{- include "renderCommonEnvs" . | indent 10 }}
{{- include "renderCryptoEnvs" . | indent 10 }}
{{- include "renderDataBaseEnvs" . | indent 10 }}
{{- include "renderRedisEnvs" . | indent 10 }}

{{- if eq .Values.messaging.type "rabbitmq" }}
{{- include "renderRabbitMQEnvs" . | indent 10 }}
{{- end }}

{{- if eq .Values.messaging.type "sqs" }}
{{- include "renderSQSEnvs" . | indent 10 }}
{{- end }}

{{- if .Values.auth.ldap.enabled }}
{{- include "renderLDAPEnvs" . | indent 10 }}
{{- end }}

{{- if .Values.auth.saml.enabled }}
{{- include "renderSAMLEnvs" . | indent 10 }}
{{- end }}

{{- if .Values.auth.openid.enabled }}
{{- include "renderOPENIDEnvs" . | indent 10 }}
{{- end }}

{{- if or (eq .Values.storage.type "S3") (eq .Values.storage.type "S3_ASYNC") }}
{{- include "renderS3Envs" . | indent 10 }}
{{- end }}

{{- if eq .Values.storage.type "CSI" }}
{{- include "renderFSEnvs" . | indent 10 }}
{{- end }}

{{- if .Values.smtp.enabled }}
{{- include "renderSMTPEnvs" . | indent 10 }}
{{- end }}

{{- if .Values.widgetsCache.enabled }}
{{- include "renderWidgetsCache" . | indent 10 }}
{{- end }}

{{- range $name, $value := .Values.env.open }}
            - name: {{ $name | quote }}
              value: {{ $value | quote }}
{{- end }}
{{- if .Values.probes.enabled }}
          startupProbe:
            httpGet:
              path: /api/management/health/readiness
              port: http
{{ toYaml .Values.probes.startup.probe | indent 12 }}
          livenessProbe:
            httpGet:
              path: /api/management/health/liveness
              port: http
{{ toYaml .Values.probes.liveness.probe | indent 12 }}
          readinessProbe:
            httpGet:
              path: /api/management/health/liveness
              port: http
{{ toYaml .Values.probes.readiness.probe | indent 12 }}
{{- end }}
{{- with .Values.resources }}
          resources:
{{ toYaml . | indent 12 }}
{{- end }}
          volumeMounts:
{{- if eq .Values.storage.type "CSI" }}
            - mountPath: {{ .Values.storage.csi.mountPoint }}
              name: storage
{{- end }}
{{- if .Values.vault.enabled }}
            - name: vault-creds
              mountPath: "{{ .Values.vault.mountPath }}"
              readOnly: true
{{- end }}
{{- if .Values.certificates.configmapName }}
            - name: ssl-path
              mountPath: "/etc/pki/ca-trust/extracted"
{{- end }}
{{- range .Values.customContainers }}
        - name: {{ .name }}
          image: {{ .image | quote }}
          command: {{ toYaml .command | nindent 12 }}
          args: {{ toYaml .args | nindent 12 }}
          resources:
{{ toYaml .resources | indent 12 }}
{{- end }}
      volumes:
{{- if eq .Values.storage.type "CSI" }}
        - name: storage
          persistentVolumeClaim:
            claimName: {{ template "testops.fullname" . }}
{{- end }}
{{- if .Values.vault.enabled }}
        - name: vault-creds
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: {{ template "testops.fullname" . }}
{{- end }}
{{- if .Values.certificates.configmapName }}
        - name: certs
          configMap:
            name: {{ .Values.certificates.configmapName }}
        - name: ssl-path
          emptyDir: {}
{{- end }}
