{{- if .Values.monitoring.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "testops.fullname" . }}-monitor
  labels:
    app: {{ template "testops.fullname" . }}
spec:
  selector:
    matchLabels:
      app: {{ template "testops.fullname" . }}
      version: v1
  endpoints:
    - port: http
      path: "/api/management/prometheus"
      interval: 10s
      honorLabels: true
{{- end }}
