{{- if .Values.image.authRequired.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.image.authRequired.credsKubeSecretName }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}
