{{- if and (not .Values.externalSecrets.enabled) (not .Values.vault.enabled)}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "testops.fullname" . }}
  labels:
    app: {{ template "testops.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:

{{- if .Values.jwtSecret }}
  jwtSecret: {{ .Values.jwtSecret | b64enc | quote }}
{{- else }}
  jwtSecret: {{ randAlphaNum 64 | b64enc | quote }}
{{- end }}

{{- if .Values.cryptoPass }}
  cryptoPass: {{ .Values.cryptoPass | b64enc | quote }}
{{- else }}
  cryptoPass: {{ randAlphaNum 64 | b64enc | quote }}
{{- end }}

  rabbitUser: {{ .Values.rabbitmq.auth.username | b64enc | quote }}
  rabbitPass: {{ .Values.rabbitmq.auth.password | b64enc | quote }}

{{- if not .Values.postgresql.enabled }}
  testopsDbUser: {{ .Values.datasources.mainDatasource.username | b64enc | quote }}
  testopsDbPass: {{ .Values.datasources.mainDatasource.password | b64enc | quote }}
{{- else }}
  testopsDbUser: {{ .Values.postgresql.auth.username | b64enc | quote }}
  testopsDbPass: {{ .Values.postgresql.auth.password | b64enc | quote }}
{{- end }}

{{- if .Values.datasources.analyticsDatasource.enabled }}
  analyticsDbUser: {{ .Values.datasources.analyticsDatasource.username | b64enc | quote }}
  analyticsDbPass: {{ .Values.datasources.analyticsDatasource.password | b64enc | quote }}
{{- end }}

{{- if .Values.minio.enabled }}
  s3AccessKey: {{ .Values.minio.auth.rootUser | b64enc | quote }}
  s3SecretKey: {{ .Values.minio.auth.rootPassword | b64enc | quote }}
{{- else }}
  s3AccessKey: {{ .Values.storage.s3.accessKey | b64enc | quote }}
  s3SecretKey: {{ .Values.storage.s3.secretKey | b64enc | quote }}
{{- end}}

  redisPass: {{ .Values.redis.auth.password | b64enc | quote }}

{{- if .Values.smtp.enabled }}
  smtpUsername: {{ .Values.smtp.username | b64enc | quote }}
  smtpPassword: {{ .Values.smtp.password | b64enc | quote }}
{{- end }}

{{- if .Values.auth.ldap.enabled }}
  ldapUser: {{ .Values.auth.ldap.auth.user | b64enc | quote }}
  ldapPass: {{ .Values.auth.ldap.auth.pass | b64enc | quote }}
{{- end }}

{{- if .Values.auth.openid.enabled }}
  openIdClientSecret: {{ .Values.auth.openid.clientSecret | b64enc | quote }}
  openIdClientId: {{ .Values.auth.openid.clientId | b64enc | quote }}
{{- end }}

{{- end }}
