name: Lint and Test Charts

on:
  pull_request:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

jobs:
  lint-test:
    runs-on: cpu16
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.0
        with:
          version: v3.8.0

      - name: Run chart-testing (lint)
        run: ct lint --config ct.yaml --debug

      - name: Create kind cluster
        uses: helm/kind-action@v1.8.0
        
      - name: Debug OIDC
        run: |
          [ -n "$ACTIONS_ID_TOKEN_REQUEST_TOKEN" ] && echo "oidc=yes" || echo "oidc=no"
          [ -n "$ACTIONS_ID_TOKEN_REQUEST_URL" ] && echo "oidc_url=yes" || echo "oidc_url=no"
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::611761462372:role/ci_ecr
          aws-region: eu-central-1

      - name: Get ECR token
        run: |
          AWS_REGION="${AWS_REGION:-eu-central-1}"
          ECR_PASSWORD="$(aws ecr get-login-password --region "$AWS_REGION")"
          echo "::add-mask::$ECR_PASSWORD"
          echo "ECR_USERNAME=AWS" >> "$GITHUB_ENV"
          echo "ECR_PASSWORD=$ECR_PASSWORD" >> "$GITHUB_ENV"

      - name: Run chart-testing (install)
        timeout-minutes: 10
        run: |
          # Define all extra arguments for Helm in a bash array for readability
          EXTRA_ARGS=(
            "--set=smtp.enabled=false"
            "--set=postgresql.enabled=true"
            "--set=minio.enabled=true"
            "--set=image.authRequired.enabled=true"
            "--set=image.registry=${{ secrets.ECR_REGISTRY }}"
            "--set-string=image.repository="
            "--set=image.imageName=testops-on-premise"
            "--set=image.authRequired.credsKubeSecretName=qameta-secret"
            "--set=image.authRequired.username=${ECR_USERNAME}"
            "--set-string=image.authRequired.password=${ECR_PASSWORD}"
            "--set=probes.enabled=false"
          )

          ct install --config ct.yaml --helm-extra-set-args "${EXTRA_ARGS[*]}"
